# This is completly bogus data. However because of the way Cucumber works
# all features and steps get initialised when we run Quke, its just that during
# CI we then choose to only run those tagged @ci.
# As some of the page objects expect there to be data read in from a .config.yml
# the build will fail if there isn't one.
# Hence this is here just to cater for just for this specific scenario
custom:
  environment: "dev" # choose from: dev qa sand
  accounts:
    PermitingSupportAdvisor:
      username: psa@example.com
      password: please123
    account2:
      username: account2@example.com
      password: please123
  urls:
    qa:
      front_office: "https://example.com"
      back_office: "https://example.com"
      external_application: "https://example.com"
    dev:
      front_office: "https://wal-dev.aws.defra.cloud/welcome"
      front_office_sign_in: "https://wal-dev.aws.defra.cloud/signin"
      external_application: "https://wal-dev.aws.defra.cloud/"
      internal_application: "https://wal-admin-dev.aws.defra.cloud/"
      root_url: "https://wal-dev.aws.defra.cloud/"
      back_office_root: "https://wal-admin-dev.aws.defra.cloud/admin/"
      back_office_login: "https://andrew.hick@environment-agency.gov.uk:Bag0nail$@wal-admin-dev.aws.defra.cloud/admin/"
    sand:
      front_office: "https://example.com"
      back_office: "https://example.com"
      back_office_internal_root: "https://example.com"
      root_url: "https://example.com"
      external_application: "https://example.com"
